"""
Step 5: GitHub Publishing

Writes lessons to files and commits to git repository.
"""

from pathlib import Path
from src.models import AgentState
from src.tools.git_operations import commit_changes, push_to_remote


def publish_node(state: AgentState) -> dict:
    """
    Write README and commit to git.

    Note: Lesson files are already written by writing_node.
    This step creates the README and commits everything.

    Args:
        state: Current agent state

    Returns:
        Dictionary with github_repo_url update
    """
    print("\n[Step 5] Publishing to repository...")

    repo_info = state['repo_info']
    lessons = state['lessons']
    topic = state['topic']

    repo_path = Path(repo_info['path'])
    lessons_dir = Path(repo_info['lessons_dir'])

    # Write README
    readme_path = repo_path / "README.md"
    readme_content = generate_readme(topic, state['target_audience'], lessons)
    readme_path.write_text(readme_content, encoding='utf-8')
    print(f"  ✓ Created README.md")

    # Lesson files are already written by writing_node
    # Just verify they exist
    existing_lessons = list(lessons_dir.glob("*.md"))
    print(f"  ✓ Found {len(existing_lessons)} lesson files")

    # Commit changes
    try:
        commit_message = f"Add course: {topic}\n\nGenerated by Research & Teaching Agent"
        commit_changes(repo_path, commit_message)
        print(f"  ✓ Committed changes")
    except Exception as e:
        print(f"  ⚠ Commit warning: {e}")

    # Try to push if remote is configured
    remote_url = repo_info.get('remote_url')
    github_repo_url = remote_url or f"file://{repo_path}"

    if remote_url:
        try:
            push_to_remote(repo_path)
            print(f"  ✓ Pushed to remote: {remote_url}")
        except Exception as e:
            print(f"  ⚠ Push failed: {e}")
            print(f"  → Repository available locally at: {repo_path}")

    print(f"\n  ✓ Publishing complete!\n")

    return {
        "github_repo_url": github_repo_url
    }


def generate_readme(topic: str, target_audience: str, lessons: dict) -> str:
    """Generate README content for the course."""

    lesson_list = []
    for i, lesson_key in enumerate(sorted(lessons.keys()), 1):
        # Extract title from filename
        title = lesson_key.replace('lesson_', '').replace('_', ' ').title()
        # Remove leading numbers
        title = ' '.join(title.split()[1:]) if title.split()[0].isdigit() else title

        lesson_list.append(f"{i}. [{title}](lessons/{lesson_key}.md)")

    lessons_md = '\n'.join(lesson_list)

    return f"""# {topic}

**Target Audience:** {target_audience}

## Course Overview

This course provides a comprehensive introduction to {topic}.

## Lessons

{lessons_md}

## About

This course was generated by the Research & Teaching Agent, which combines:
- Web research via Tavily API
- Knowledge synthesis by Claude Sonnet-4
- Pedagogical writing by Claude Sonnet-4

The content is designed for self-study and follows a progressive learning structure.

## License

This educational content is provided as-is for learning purposes.
"""
